#!/bin/bash
# Mirrors this repo's skills and commands into .agents/ and .codex/ so
# Cursor and Codex see the same thing Claude Code does.
#
# Claude Code reads .claude/skills/ and .claude/commands/ directly.
# Cursor reads .claude/skills/, .claude/commands/, AND .agents/ — but a
# mirror still helps tools in the same family that only look at .agents/.
# Codex reads ONLY .codex/skills/ and AGENTS.md — it has no concept of
# .claude/commands/ at all, so each command needs a small shim skill
# instead of a plain copy.
#
# Canon (the only thing you edit):
#   .claude/skills/<name>/SKILL.md
#   .claude/commands/<name>.md
#
# Generated by this script (don't hand-edit, it gets overwritten):
#   .agents/skills/<name>          -> symlink to ../../.claude/skills/<name>
#   .agents/commands/<name>.md     -> symlink to ../../.claude/commands/<name>.md
#   .codex/skills/<name>           -> symlink to ../../.claude/skills/<name>
#   .codex/skills/cmd-<name>/      -> a shim SKILL.md pointing at the real command
#
# Run this from the repo root after adding, renaming, or removing a skill
# or command:
#   System/scripts/sync-agent-mirrors.sh          # apply
#   System/scripts/sync-agent-mirrors.sh --dry     # show what it would do

set -u
cd "$(dirname "$0")/../.." || exit 1

DRY=0
[ "${1:-}" = "--dry" ] && DRY=1

# Git Bash on Windows: `ln -s` silently makes a copy (or fails), and git
# still expects a symlink. Only the cmd-* shims (plain files) are made here;
# the links are handled by setup-symlinks.py, which knows how to copy safely.
WIN=0
case "$(uname -s)" in MINGW*|MSYS*|CYGWIN*) WIN=1 ;; esac
run() { if [ $DRY -eq 1 ]; then echo "  [dry] $*"; else "$@"; fi; }

[ -d ".claude/skills" ] || { echo "No .claude/skills/ here — run this from the repo root."; exit 1; }

sync_symlink_dir() {  # <dest-dir> <name> <relative-target>
  local dest="$1/$2" rel="$3"
  [ $WIN -eq 1 ] && return
  if [ -L "$dest" ]; then
    [ "$(readlink "$dest")" = "$rel" ] && return
    run rm -f "$dest"
  elif [ -e "$dest" ]; then
    echo "  ! $2 already exists as a real file/dir under $1 — skipping, check by hand"
    return
  fi
  echo "  + $1/$2"
  run ln -s "$rel" "$dest"
}

drop_dead_links() {  # <dir>
  for link in "$1"/*; do
    [ -L "$link" ] || continue
    [ -e "$link" ] && continue
    echo "  - dead: $1/$(basename "$link")"
    run rm -f "$link"
  done
}

echo "=== skill mirrors: .agents/skills, .codex/skills ==="
for T in ".agents/skills" ".codex/skills"; do
  run mkdir -p "$T"
  drop_dead_links "$T"
  for skill in .claude/skills/*/; do
    [ -d "$skill" ] || continue
    name=$(basename "$skill")
    sync_symlink_dir "$T" "$name" "../../.claude/skills/$name"
  done
done

echo "=== command mirrors: .agents/commands ==="
run mkdir -p ".agents/commands"
drop_dead_links ".agents/commands"
for cmd in .claude/commands/*.md; do
  [ -f "$cmd" ] || continue
  base=$(basename "$cmd")
  sync_symlink_dir ".agents/commands" "$base" "../../.claude/commands/$base"
done

echo "=== .codex/skills/cmd-* — command shims (Codex has no .claude/commands/) ==="
for cmd in .claude/commands/*.md; do
  [ -f "$cmd" ] || continue
  name=$(basename "$cmd" .md)
  desc=$(sed -n 's/^description: *//p' "$cmd" | head -1)
  [ -n "$desc" ] || desc="Project command /$name"
  dest=".codex/skills/cmd-$name"

  echo "  + shim cmd-$name"
  [ $DRY -eq 1 ] && continue
  mkdir -p "$dest"
  cat > "$dest/SKILL.md" <<EOF
---
name: cmd-$name
description: "/$name — $desc"
---

# /$name

Shim generated by \`System/scripts/sync-agent-mirrors.sh\`. **Don't edit this
file** — the next run overwrites it.

It exists because Codex doesn't read \`.claude/commands/\`, while Claude Code
and Cursor do. Rather than copy the command's text here (copies rot — the
canon changes and the copy doesn't), this file just points at the original.

## What to do

Read **\`.claude/commands/$name.md\`** at this repo's root and follow it
literally, as your own instructions. That's the only source of truth for
this command — the description above exists only so you know when to run it.
EOF
done

echo
if [ $WIN -eq 1 ]; then
  echo "Windows: symlinks skipped. Now run:  py System/scripts/setup-symlinks.py"
fi
echo "Done. Restart the session in Codex/Cursor to see the changes."
